backend:
  name: git-gateway
  branch: master # Branch to update

media_folder: "_site/images/uploads"
public_folder: "/images/uploads"

collections:
 - name: "events" #The name of the collection and should match our posts.json file's tag
   label: "Events" #The name of the collection on the CMS itself
    folder: "events" #The folder that our blog posts will be loaded from and saved to
    create: true #Tells the CMS that new posts can be created
    slug: "{{slug}}" #this sets the URL for the post
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date", default: "" }
      - { label: "Time", name: "time", widget: "string" }
      - { label: "Venue", name: "venue", widget: "string" }
      - { label: "Venue URL", name: "venueURL", widget: "string" }
      - { label: "Performers", name: "performers", widget: "string" }
      - { label: "Additional Info", name: "info", widget: "string" }
      - { label: "Flyer", name: "flyer", widget: "image" }
