backend:
  name: github
  repo: TimothyOD/ynkyk

media_folder: "_site/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "events"
    label: "Events"
    folder: "events"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date/Time",
          name: "date",
          widget: "datetime",
          default: "",
          dateFormat: "DD.MM.YYYY", # e.g. 24.12.2021
          timeFormat: "HH:mm", # e.g. 21:07
          format: "LLL",
          pickerUtc: false,
        }
      - { label: "Time", name: "time", widget: "string" }
      - { label: "Venue", name: "venue", widget: "string" }
      - {
          label: "Venue URL",
          name: "venueURL",
          widget: "string",
          required: false,
        }
      - { label: "Performers", name: "performers", widget: "string" }
      - {
          label: "Additional Info",
          name: "info",
          widget: "string",
          required: false,
        }
      - { label: "Flyer", name: "flyer", widget: "image" }
